### ISSUE TITLE
Get into "Add new services" list

### ISSUE THREAD

**Issue by gsf** [yoichiro/chromeos-filesystem-sftp#71]
Seeing this in the dev channel of ChromeOS:

![screenshot 2015-04-09 at 15 53 48](https://cloud.githubusercontent.com/assets/151913/7075525/b98256c8-ded0-11e4-85fd-a31c7233632a.png)

When clicked I get this list:

![screenshot 2015-04-09 at 15 55 20](https://cloud.githubusercontent.com/assets/151913/7075539/dc1db6a0-ded0-11e4-8921-6736e4f82d58.png)

Seems like sftpfs should be in there!

**Comment by yoichiro** [comment]
@gsf Have the SFTP File System already been installed into your Chromebook?

**Comment by gsf** [comment]
Yes. I'm guessing there's a new ChromeOS API for this since I'm just seeing it now on the dev channel.

**Comment by yoichiro** [comment]
@gsf Probably, this list means that "A provider list which you don't install yet". Actually, I faced the message "not found", because I have already installed all providers. I guess that this behavior (sftp provider was not listed) is as the specification of the "add new services" feature. As thre result, I guess that any APIs never be provided from ChromeOS... Maybe...

**Comment by mtomasz-chromium** [comment]
Correct. We're going to improve it and show also installed providers in a convenient way. Stay tuned.

**Comment by gsf** [comment]
Excellent. No work to be done here then.

**Comment by kmc8ij1** [comment]
How do i get this off of my Chromebook? I didn't ask for it, I don't want it.
